// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8KKxlEhAxFVp9AEL-EeYWeZolLWzIOws',
    appId: '1:691292374218:web:9a6df23782141a233d2033',
    messagingSenderId: '691292374218',
    projectId: 'pawshelter-6th-semester',
    authDomain: 'pawshelter-6th-semester.firebaseapp.com',
    storageBucket: 'pawshelter-6th-semester.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgVOmJ9_JrzNv-eU9IEaaDloLqcHtstAg',
    appId: '1:691292374218:android:3e19c50d866ab5ec3d2033',
    messagingSenderId: '691292374218',
    projectId: 'pawshelter-6th-semester',
    storageBucket: 'pawshelter-6th-semester.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA_NGYkfCxJXCKju3h-5xsUZcihPKvxOk',
    appId: '1:691292374218:ios:600f815bc63175cf3d2033',
    messagingSenderId: '691292374218',
    projectId: 'pawshelter-6th-semester',
    storageBucket: 'pawshelter-6th-semester.firebasestorage.app',
    iosBundleId: 'com.example.glitched',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA_NGYkfCxJXCKju3h-5xsUZcihPKvxOk',
    appId: '1:691292374218:ios:600f815bc63175cf3d2033',
    messagingSenderId: '691292374218',
    projectId: 'pawshelter-6th-semester',
    storageBucket: 'pawshelter-6th-semester.firebasestorage.app',
    iosBundleId: 'com.example.glitched',
  );

}